### PR TITLE
Migrate to JUnit 5

### PR DESCRIPTION
**Pull request by BlueIce**
Ready to be merged.

JUnit 4 tests are still run by JUnit 5.

Additionally bumped Gradle version to 4.3.1

### CODE REVIEW

**Review by UrsMetz — APPROVED** [review]
LGTM.
One thing I noticed: The `build.gradle` file now uses double quote strings for interpolation but single quote strings for non interpolating strings. Should we use double quotes for all strings? I don't know what the recommended style is. Maybe using double quotes only when necessary is a good thing because this tells the programmer that interpolation is happening.

**Comment by almondtools** [comment]
I think your point is right. Nobody would expect that the difference in quotes is semantically justified. So migrating to double quotes seems a good resolution.

Yet I am not certain whether versions should be stored in variables. I am accustomed to read the information which version is used for a dependencies from the line where it is defined. Storing version information separately is less readable and inhibits frequent version updates.

So perhaps we should discuss to inline all version information instead of using interpolated strings.

**Comment by BlueIce** [comment]
@UrsMetz, @almondtools: I updated the pull request. The version definitions are "inlined" and use single quotes (as before). Concerning quotes the Groovy language guide says (http://groovy-lang.org/style-guide.html):

> Last but not least, prefer using single quoted strings when you need string constants, and use double quoted strings when you are explicitly relying on string interpolation.

If we still want to change to double quotes i think we should discuss this in an separate issue/pull request.

**Comment by UrsMetz** [comment]
Actually I lean towards using version variables that are then referenced via interpolation because it reduces duplication and makes it harder to miss updating related dependencies.
But I also think we should merge this one and discuss the quote question (and whether we want to use centralized version string variables).
@almondtools are you fine with merging this one?

**Comment by UrsMetz** [comment]
@BlueIce @almondtools I created #19 for discussion the style questions

**Review by almondtools — APPROVED** [review]

**Pull request merged**
